# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Event.create(name:"Hal Foster: Bad New Days", time: "2015-09-16T19:00:00-0400", description: "The Kitchen is pleased to present Bad New Days: Art, Criticism, Emergency; a reading and book signing by Hal Foster with interlocutor Tim Griffin. Bad New Days: Art, Criticism, Emergency by Hal Foster examines the evolution of art and criticism in Western Europe and North America over the last 25 years, and their dynamic relation to the general condition of emergency instilled by neoliberalism and the war on terror. Considering the work of artists such as Thomas Hirschhorn, Tacita Dean, and Isa Genzken, and the writing of thinkers like Jacques Rancière, Bruno Latour, and Giorgio Agamben, Hal Foster shows the ways in which art has anticipated this condition, at times resisting the collapse of the social contract or gesturing toward its repair; at other times burlesquing it. Against the claim that art making has become so heterogeneous as to defy historical analysis, Foster argues that the critic must still articulate a clear account of the contemporary in all its complexity. To that end, he offers several paradigms for the art of recent years, which he terms “abject,” “archival,” “mimetic,” and “precarious.” Hal Foster is Townsend Martin Professor of Art and Archaeology at Princeton University and a 2014–15 fellow at the Cullman Center for Scholars and Writers at the New York Public Library. A co-editor of October magazine and books, he is the editor of The Anti-Aesthetic and the author of Design and Crime, Recording, The Return of the Real, Compulsive Beauty and The Art-Architecture Complex. Verso Books—the left-hand page—was launched as a paperback imprint of New Left Books at the end of the seventies. Since becoming NLB’s sole imprint, Verso Books has grown to be the largest independent, radical publishing house in the English-speaking world, publishing one hundred books a year. September 16, 7pm FREE")
Event.create(name:"Pisockophilia", time: "2015-09-27T21:05:00-0400", description: "STUX + HALLER (24 W 57th Street) is pleased to announce Pisockophilia, new paintings by New York artist Aaron Johnson. Through March 21st. The exhibition features his two distinctive and wildly innovative approaches to painting. The newest developments in Johnsonʼs oeuvre are his “sock paintings” which display a rugged counterpoint to the “reverse painted acrylic polymer peel paintings” for which Johnson has been well known. These two processes in their divergent physicality have brewed in symbiosis from opposite sides of the picture plane, working in tandem to illuminate Aaron Johnsonʼs phantasmagorical vision.")
Event.create(name:"And If The Devil Is Six...", time: "2015-02-27T18:00:00-0500", description: "Opening February 27, 6-9 pm Station Independent Projects 138 Eldridge Street, 2nd Fl 'And if the Devil is Six...  brings together Jain's paintings from the last few years, envisioning the symbolic body as seen through different cultures and time periods. Working with casein paint directly on wood, augmented by silver, gold mica and black mica and wood carving, these works bring together diverse sources including Eastern and new age spiritualism, phrenology, body shape charts and thermal imaging, and juxtapose them with the colors of the prismatic spectrum. Vandana Jain is an artist and textile designer based in Brooklyn, NY. She received her Bachelor’s from NYU and went on to study Textile Design at FIT. Her work explores the intersections of pattern and symbol, and spirituality and consumerism. This is her second show at Station Independent Projects. Please Join us @ March 7th from Noon-6pm for the Lower East Side Armory Art Week Gallery Stroll")
Event.create(name:"Another Green World: An Economic Proposal",  time: "2014-09-12T17:00:00-0400", description: "Another Green World: An Economic Proposal Curated by Keith Miller Melanie Baker, Brad DeCecco, Joseph Heidecker, Mitch Joachim, Nina Katchadourian, Steve Lambert (and others) with Post Carbon Institute, William Lamson, Ashley Panzera, Rachel Sussman, Kathleen Vance Our relationship to the environment is an economic proposal. Who profits and who suffers,how we use and think about natural resources and what are the consequences of these decisions: these questions are at the heart of the climate issue. It is more and more urgent that we keep this plain fact present. When climate change is denied, it is an economic struggle. The science is clear: climate change is real. But so are the economics: to change practices and ways of thinking will have an economic impact.It is that challenge to existing uses and practices which is denied. For those willing to accept the judgment of 97 of the scientific community’s data, the problem is ethical, economic, practical or spiritual, and often enough, all of these at once. Another Green World looks at these issues through the works of artists who have engaged with the problem in ways scientific and personal, practical and political. Documenting the issue soberly and clearly is one approach. Another is to treat the issue as a practical problem, which can be addressed through ingenuity and the transformation of our habits and lifestyles. As with so many of the issues that face our world today, the current impending environmental catastrophe is a child of the Modern period. Industrialization made distances shorter just as it made raw materials more needed and more quickly devoured, land more deeply mined and forests more quickly made bare. Before this period, there was a green world, which though changing, had remained constant for millennia. As we look to our present in the light of the impending change to come, the artists here wonder aloud how to make Another Green World.")
Event.create(name:"UNDERLINE : Recent work by Judy Yang", time: "2015-02-06T18:00:00-0500", description: "Whitebox Art Center presents 'Underline', recent work by Judy Yang Curated by Lucila Gradin White Box Art Center 329 Broome Street (Between Bowery and Chrystie) New York, NY 10002 www.whiteboxny.org Reception | Friday, February 6th, 2015 6 ~ 8 pm Dates | February 4th through February 25th, 2015 Hours | 11am to 6pm, Monday through Sunday Direction | 6 to Spring Street J/Z to Bowery B/D to Grand New York City – Underline is an exhibition presenting recent work by Joo Jeon Judy Yang, curated by Argentine curator Lucila Gradin. Judy Yang’s work arises from the artist’s own merging of visual traditions wrought from her East Asian lineage and Western experience, evoking coded landscapes and meticulously layered architectural renderings, taking influences from religious myth and social catastrophes, to talk about the political consequences of media manipulation. In the exhibition there will be two bodies of work in dialogue. On one side Judy Yang will present three large-scale scraped boards from her series “Mistreatment of Life,” developed after the artist’s own first-hand experience of the 2010 foot-and-mouth disease (FMD) outbreak, after which Yang began to question the economy of food and health in our society. On the other side of the exhibition space, seven currency collages from the series “One Nation Banknote” will be displayed, recomposing the idealized iconography of real international currency to reveal an underlying narrative of social catastrophe. These formally engaging, rigorous and labor-intensive works reference on one hand the vertical spaces and textured expanses of Asian scroll painting landscapes, while simultaneously calling to mind the heavily etched lines influenced by Western print masters. This collection of pieces demands close examination: a slow, careful review akin to the study of evidence. Such a forensic visual investigation prompts the exploration of different approaches to morality through the highly detailed spaces of an East/West hybrid, filtered through the artist’s deft hand and careful, sensitive rendering. The title of the show references the crawling television news ticker, which the artist interprets as the bearer of real information in the face of the distracting, manipulated spectacle of the images “breaking” on the screen. Curated by Lucila Gradin")
Event.create(name:"Random Numbers",  time: "3pm", description: "Description Here")
Event.create(name:"Like Events", time: "1pm", description: "Description Here")

puts Event.all
